name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: 
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Project
        run: ./gradlew build
        
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Run Tests
        run: ./gradlew test
